export const SET_SEARCH = 'SET_SEARCH'
export const MEDIA_URL = 'https://image.tmdb.org/t/p/w1920_and_h800_multi_faces'
export const BACKDROP_URL = 'https://www.themoviedb.org/t/p/w220_and_h330_face'
export const AUTHOR_IMAGE_URL = 'https://image.tmdb.org/t/p/w138_and_h175_face'
export const ORIGINAL_IMAGE_URL = 'https://image.tmdb.org/t/p/original'
export const IMDB_SINGLE_URL = 'http://www.imdb.com/title'
